#ifndef IMAGE_STRUCTH
#define IMAGE_STRUCTH

// Macro POS_VAR_LEADERBOARD
#define FIRST_NAME_POS_Y 295
#define LEADERBOARD_SEPARATION 45

// Macro POS_SEEDS_AWALE
#define SEED_WIDTH 50
#define SEED_HEIGHT 50
#define AWALE_1ST_SEED_POS_X 375
#define AWALE_P2_1ST_SEED_POS_Y 275
#define AWALE_P1_1ST_SEED_POS_Y 405
#define SEED_SEPARATION 100

//Macro POS_NUMBER_OF_SEED
#define POS_X_1ST_NUMBER_OF_SEED 385
#define SEPARATION_NUMBER_OF_SEED 98
#define POS_Y_NUMBER_OF_SEED_PLAYER2 173
#define POS_Y_NUMBER_OF_SEED_PLAYER1 523

#endif